export const cows = [
  {
    id: '07',
    name: 'Marguerite',
    breed: 'Holstein',
    age: 4,
    status: 'danger',
    statusLabel: 'Hors zone',
    statusLabel_ar: 'خارج المنطقة',
    metric: '!',
    metricUnit: '',
    metricColor: 'red',
    temp: 38.6,
    activity: 'Hors zone sécurisée',
    activity_ar: 'خارج المنطقة الآمنة',
    gpsActive: true,
    milkToday: 0,
    gestationDay: null,
  },
  {
    id: '12',
    name: 'Rosette',
    breed: 'Montbéliarde',
    age: 3,
    status: 'warn',
    statusLabel: 'Surveiller',
    statusLabel_ar: 'للمراقبة',
    metric: '39.8°C',
    metricUnit: '',
    metricColor: 'amber',
    temp: 39.8,
    activity: 'Température élevée',
    activity_ar: 'ارتفاع في الحرارة',
    gpsActive: true,
    milkToday: 18,
    gestationDay: null,
  },
  {
    id: '03',
    name: 'Blanchette',
    breed: 'Holstein',
    age: 5,
    status: 'ok',
    statusLabel: 'OK',
    statusLabel_ar: 'جيد',
    metric: '28L',
    metricUnit: "aujourd'hui",
    metricUnit_ar: 'اليوم',
    metricColor: 'green',
    temp: 38.4,
    activity: 'Production optimale',
    activity_ar: 'إنتاج ممتاز',
    gpsActive: true,
    milkToday: 28,
    gestationDay: null,
  },
  {
    id: '05',
    name: 'Noisette',
    breed: "Prim'Holstein",
    age: 3,
    status: 'info',
    statusLabel: 'Gestation',
    statusLabel_ar: 'حمل',
    metric: 'J+214',
    metricUnit: '',
    metricColor: 'teal',
    temp: 38.5,
    activity: 'Gestation normale',
    activity_ar: 'حمل طبيعي',
    gpsActive: true,
    milkToday: 12,
    gestationDay: 214,
  },
  {
    id: '09',
    name: 'Bellina',
    breed: 'Montbéliarde',
    age: 6,
    status: 'ok',
    statusLabel: 'OK',
    statusLabel_ar: 'جيد',
    metric: '24L',
    metricUnit: "aujourd'hui",
    metricUnit_ar: 'اليوم',
    metricColor: 'green',
    temp: 38.3,
    activity: 'Comportement normal',
    activity_ar: 'سلوك طبيعي',
    gpsActive: true,
    milkToday: 24,
    gestationDay: null,
  },
];

export const alerts = [
  {
    id: 1,
    type: 'danger',
    text: 'Vache #07 — Marguerite : sortie de zone sécurisée',
    text_ar: 'البقرة #07 — مارجريت: خروج من المنطقة الآمنة',
    time: 'Il y a 12 min',
    time_ar: 'منذ 12 دقيقة',
    label: 'Urgent',
    label_ar: 'عاجل',
    icon: '📍',
  },
  {
    id: 2,
    type: 'warn',
    text: 'Vache #12 — Rosette : température 39.8°C',
    text_ar: 'البقرة #12 — روزيت: حرارة 39.8°',
    time: 'Il y a 38 min',
    time_ar: 'منذ 38 دقيقة',
    label: 'Surveiller',
    label_ar: 'مراقبة',
    icon: '🌡️',
  },
  {
    id: 3,
    type: 'ok',
    text: 'Collier #03 : batterie rechargée (solaire)',
    text_ar: 'الطوق #03: تم شحن البطارية (شمسي)',
    time: 'Il y a 1h',
    time_ar: 'منذ ساعة',
    label: 'OK',
    label_ar: 'جيد',
    icon: '🔋',
  },
];

export const milkData = [
  { day: 'Lun', value: 165 },
  { day: 'Mar', value: 178 },
  { day: 'Mer', value: 171 },
  { day: 'Jeu', value: 190 },
  { day: 'Ven', value: 184 },
  { day: 'Sam', value: 176 },
  { day: 'Dim', value: 186 },
];

/** Données météo (maquette — à brancher sur une API plus tard) */
export const weatherFarm = {
  location: 'Ferme Al-Baraka',
  region: 'Nord — plaine',
  region_ar: 'الشمال — السهل',
  summary: 'Partiellement nuageux',
  summary_ar: 'غائم جزئياً',
  icon: '⛅',
  temp: 22,
  feelsLike: 20,
  humidity: 65,
  windKmh: 14,
  windDir: 'NO',
  pastureHint: 'Conditions favorables au pâturage cet après-midi.',
  pastureHint_ar: 'ظروف مناسبة للرعي هذا المساء.',
  updated: '10:42',
};

export const aiRisks = [
  {
    id: 1,
    cowName: 'Rosette #12',
    risk: 'Mastite probable',
    risk_ar: 'اشتباه التهاب الضرع',
    probability: 72,
    severity: 'warn',
    description:
      'Comportement de rumination réduit de 34% sur 48h. Température légèrement élevée. Recommandation : examen vétérinaire dans les 24h.',
    description_ar:
      'انخفاض الاجترار بنسبة 34% خلال 48 ساعة. حرارة مرتفعة قليلاً. التوصية: فحص بيطري خلال 24 ساعة.',
  },
  {
    id: 2,
    cowName: 'Noisette #05',
    risk: 'Chaleur prochaine',
    risk_ar: 'قرب الدخول في الشبق',
    probability: 88,
    severity: 'info',
    description:
      "Activité accrue détectée par l'accéléromètre. Période d'insémination optimale estimée dans 3 jours. Rappel programmé.",
    description_ar:
      'تم رصد نشاط مرتفع بواسطة المستشعر. أفضل وقت للتلقيح خلال 3 أيام. تم جدولة تذكير.',
  },
];

export const behaviorData = [
  { label: 'Repos / Couchées', label_ar: 'راحة / استلقاء', value: 58, color: 'teal' },
  { label: 'Rumination', label_ar: 'اجترار', value: 22, color: 'green' },
  { label: 'Marche / Active', label_ar: 'مشي / نشاط', value: 15, color: 'amber' },
  { label: 'Alimentation', label_ar: 'تغذية', value: 5, color: 'green' },
];
