# Generated by Django 6.0.4 on 2026-05-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cows/'),
        ),
        migrations.AddField(
            model_name='cow',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
