# Generated by Django 5.2.12 on 2026-04-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_conversationsummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='role',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='session_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
